GPIB-450
dltxio/v2.getpaidinbitcoin.com.au pull request #109
Opened 2021-06-03 07:05 UTC by SharmaDinesh

2021-06-03 07:19 UTC, rellfy requested changes
Just a few lines that can be removed

2021-06-03 07:19 UTC, rellfy commented on src/components/deposit-hints/DepositHintsForm.js
> +  // };
```suggestion
```

2021-06-03 23:33 UTC, SharmaDinesh commented on src/components/deposit-hints/DepositHintsForm.js
> +  // };
Done

2021-06-04 00:11 UTC, ahinchliff approved these changes

2021-06-04 00:13 UTC, xiangzhe0812 reviewed
one little change

2021-06-04 00:13 UTC, xiangzhe0812 commented on src/components/deposit-hints/DepositHintsForm.js
> +
if(!values.depositAmount) errors.depositAmount = requireMsg;
if(values.depositAmount && !re.test(values.depositAmount))  errors.depositAmount = depositAmountMsg

2021-06-04 00:13 UTC, xiangzhe0812 commented on src/components/deposit-hints/DepositHintsForm.js
> +
wo can do like above

2021-06-04 00:31 UTC, SharmaDinesh commented on src/components/deposit-hints/DepositHintsForm.js
> +
Done

2021-06-04 01:36 UTC, xiangzhe0812 approved these changes

2021-06-04 01:36 UTC, merged