GPIB-452
dltxio/v2.getpaidinbitcoin.com.au pull request #137
Opened 2022-04-14 05:58 UTC by JasminFarhi

Created reset mobile model

2022-04-18 23:32 UTC, bitcoinbrisbane commented on src/components/VerificationTracker/VerifyID.js
> +}; ///INTERESTINGGG
lol, lets remove?

2022-04-18 23:33 UTC, bitcoinbrisbane commented on src/components/VerificationTracker/VerifyMobile.js
> +
Remove?

2022-04-18 23:34 UTC, bitcoinbrisbane requested changes
Few minor changes

2022-04-18 23:54 UTC, bitcoinbrisbane approved these changes

2022-04-19 00:15 UTC, xiangzhe0812 approved these changes

2022-04-19 00:18 UTC, merged