GPIB-618
dltxio/v2.getpaidinbitcoin.com.au pull request #166
Opened 2024-03-07 01:16 UTC by rodonguyen

- [Link to ticket](https://dltx.atlassian.net/browse/GPIB-618)

before:
![image](https://github.com/dltxio/v2.getpaidinbitcoin.com.au/assets/30222384/8af37f0e-9b66-4eaa-be8d-73709f198c60)

bill is paid:
![image](https://github.com/dltxio/v2.getpaidinbitcoin.com.au/assets/30222384/996b411c-7369-417a-9a9b-7645ff30a26b)

2024-03-13 05:11 UTC, bitcoinbrisbane commented on public/index.html
> +    <script src="https://testnet.demo.btcpayserver.org/modal/btcpay.js"></script>
lets remove this guy

2024-03-13 05:11 UTC, bitcoinbrisbane requested changes
one small thing

2024-03-15 01:35 UTC, rodonguyen commented on public/index.html
> +    <script src="https://testnet.demo.btcpayserver.org/modal/btcpay.js"></script>
deleted in my next commit

2024-03-18 02:24 UTC, rodonguyen commented
this should have been implemented in a separate branch and merged into features/bills

2024-03-18 05:44 UTC, bitcoinbrisbane commented on src/pages/BillsPage.js
> +      // if (response.data?.paid) {
Whats this guy?

2024-03-18 05:44 UTC, bitcoinbrisbane commented on src/pages/BillsPage.js
> +      pollBillStatus(9999);
whats all this?

2024-03-18 05:44 UTC, bitcoinbrisbane commented on src/pages/BillsPage.js
> +  // };
Lets remove

2024-03-18 05:45 UTC, bitcoinbrisbane commented on src/pages/BillsPage.js
> +          </Button> */}
Lets remove

2024-03-18 05:45 UTC, bitcoinbrisbane commented on src/pages/BillsPage.js
> +          {/* <ErrorMessage error={fetchDepositHintsError | errorMessage} /> */}
Lets remove

2024-03-18 05:46 UTC, bitcoinbrisbane requested changes
- Create new branch as per the convention
- Address the comments

2024-03-18 06:08 UTC, rodonguyen commented
PR moved to [here](https://github.com/dltxio/v2.getpaidinbitcoin.com.au/pull/178)

2024-03-18 06:08 UTC, closed without merging