GPIB-249
dltxio/v2.getpaidinbitcoin.com.au pull request #62
Opened 2021-02-04 04:30 UTC by xiangzhe0812

This PR depend on GPIB.admin.api 's PR GPIB-249
To test 
1. run yarn start and navigate to http://localhost:3000/enterprise, expect see a Corporate onboarding page.
2. give all the information and submit, expect see success message show up and email send to Contact Email address

2021-02-04 05:17 UTC, Mitchell139 approved these changes

2021-02-04 05:32 UTC, Mitchell139 requested changes

2021-02-04 05:32 UTC, Mitchell139 commented on src/components/enterprise/EnterprisesForm.js
> +          <Input label="Payroll Information" name="payrollInformation" />
We need a "Number of Employees" input.

Also, it isn't clear from the names what the expected inputs for `Payroll Contact` and `Payroll Information` are.

2021-02-04 23:30 UTC, sjustintaylor commented on src/components/enterprise/EnterprisesForm.js
> +          <Input label="Email Domain" name="emailDomain" />
This should be more specific, or have some sort of clarification. Email domain is a little confusing. Normally for this kind of thing, we'd ask for their domain name, not their email domain.

2021-02-04 23:30 UTC, sjustintaylor commented
A few minor changes, otherwise looks good to me

2021-02-04 23:40 UTC, sjustintaylor commented on src/components/enterprise/validate.js
> +const validate = values => {
Why aren't we using Yup or Joi? There's no meaningful validation here. We could be properly validating email addresses, and urls at a mimimum (could also validate phone numbers based on length)

2021-02-04 23:42 UTC, sjustintaylor commented on src/components/enterprise/validate.js
> +const validate = values => {
We could also use Yup to validate ABN numbers based on length (strip all whitespace before validating though, that way the user can add spaces)

2021-02-04 23:54 UTC, sjustintaylor commented on src/components/enterprise/validate.js
> +const validate = values => {
As discussed, keep `validator`, add validation for urls, (validate abn on length, same for phone?)

2021-02-05 05:53 UTC, sjustintaylor commented on src/components/enterprise/validate.js
> +  if (!isMobilePhone(values.contactPhoneNumber, "en-AU"))
This will fail on a valid landline number (Otherwise, good work on the rest of the validations)

2021-02-05 05:55 UTC, sjustintaylor commented on src/components/enterprise/validate.js
> +  if (!isMobilePhone(values.contactPhoneNumber, "en-AU"))
If we're just asking for mobile numbers, then it needs to be specified in the form, if not then this should include something for landlines (modify this regex?: `/^(\+?61|0)4\d{8}$/`

2021-02-05 06:47 UTC, sjustintaylor approved these changes

2021-02-05 06:50 UTC, merged