GPIB-379
dltxio/v2.getpaidinbitcoin.com.au pull request #75
Opened 2021-02-26 00:23 UTC by xiangzhe0812

enable generate HD address

2021-02-26 01:12 UTC, Mitchell139 approved these changes

2021-02-26 03:15 UTC, rellfy approved these changes

2021-03-03 03:03 UTC, bitcoinbrisbane approved these changes

2021-03-03 03:04 UTC, bitcoinbrisbane requested changes
Actually, make this a config file / setting

2021-03-03 03:15 UTC, xiangzhe0812 commented
new story came up from Adam, ask to make change

2021-03-08 05:56 UTC, closed without merging